font:
  size: 14

window:
  padding:
    x: 4
    y: 4
  dynamic_padding: true
  decorations: none
  opacity: 0.9

schemes:
  gruvbox: &gruvbox
    primary:
      background: '#282828'
      foreground: '#ebdbb2'

    normal:
      black: '#282828'
      red: '#cc241d'
      green: '#98971a'
      yellow: '#d79921'
      blue: '#458588'
      magenta: '#b16286'
      cyan: '#689d6a'
      white: '#a89984'

    bright:
      black: '#928374'
      red: '#fb4934'
      green: '#b8bb26'
      yellow: '#fabd2f'
      blue: '#83a598'
      magenta: '#d3869b'
      cyan: '#8ec07c'
      white: '#ebdbb2'

  iceberg: &iceberg
    primary:
      background: '#161821'
      foreground: '#d2d4de'

    normal:
      black: '#161821'
      red: '#e27878'
      green: '#b4be82'
      yellow: '#e2a478'
      blue: '#84a0c6'
      magenta: '#a093c7'
      cyan: '#89b8c2'
      white: '#c6c8d1'

    bright:
      black: '#6b7089'
      red: '#e98989'
      green: '#c0ca8e'
      yellow: '#e9b189'
      blue: '#91acd1'
      magenta: '#ada0d3'
      cyan: '#95c4ce'
      white: '#d2d4de'

colors: *gruvbox
