import = [
  "~/.config/alacritty/themes/everforest_dark.toml"
]

[env]
TERM = "alacritty"

[font]
size = 14

[font.bold]
family = "Menlo"
style = "Regular"

[font.bold_italic]
family = "Menlo"
style = "Italic"

[font.italic]
family = "Menlo"
style = "Italic"

[font.normal]
family = "Menlo"
style = "Regular"

[keyboard]
bindings = [
  { key = "T", mods = "Super", action = "ReceiveChar" },
  { key = "Enter", mods = "Super", action = "ToggleFullscreen" },
]

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
dynamic_padding = false
opacity = 0.945
# startup_mode = "FullScreen"

[window.padding]
x = 5
y = 0
