# frozen_string_literal: true

cask_args appdir: '/Applications'

tap 'homebrew/cask'
tap 'aws/tap'
tap 'beeftornado/rmtree'
tap 'koekeishiya/formulae'
tap 'rs/tap'
tap 'universal-ctags/universal-ctags'
tap 'hashicorp/tap'

brew 'readline'
brew 'xz'
brew 'zlib'
brew 'imagemagick'

brew 'mysql'
brew 'redis'
brew 'sqlite3'

brew 'neovim'
brew 'universal-ctags', args: %w[HEAD]
brew 'git'
brew 'gh'
brew 'hub'
brew 'tig'
brew 'csvq'
brew 'fzf'
brew 'gnu-sed'
brew 'jq'
brew 'ripgrep'
brew 'fd'
brew 'gnupg'
brew 'coreutils'
brew 'findutils'
brew 'unar'
brew 'graphviz'
brew 'gibo'

brew 'jaggr'
brew 'jplot'
brew 'vegeta'

brew 'terraform-ls'

cask 'iterm2'
cask 'docker'
cask 'appcleaner'
cask 'insomnia'
cask 'rectangle'
cask 'table-tool'
cask 'visual-studio-code'
cask 'oracle-jdk'
cask 'sequel-ace'
cask 'google-japanese-ime'
