#!/bin/bash

set -ex

defaults write -g InitialKeyRepeat -int 25
defaults write -g KeyRepeat -int 6
defaults write -g ApplePressAndHoldEnabled -bool false
defaults write -g _HIHideMenuBar -bool true
defaults write -g AppleMenuBarVisibleInFullscreen -bool false
defaults write -g AppleShowScrollBars -string WhenScrolling
killall SystemUIServer

defaults write com.apple.dock tilesize -integer 48
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock show-recents -bool false
killall Dock

defaults write com.apple.QuickTimePlayerX NSQuitAlwaysKeepsWindows -bool false

sudo defaults write /Library/Preferences/FeatureFlags/Domain/UIKit.plist redesigned_text_cursor -dict-add Enabled -bool NO
