#!/bin/bash

defaults write -g InitialKeyRepeat -int 25
defaults write -g KeyRepeat -int 6
defaults write -g ApplePressAndHoldEnabled -bool false
defaults write com.apple.dock tilesize -integer 48 && killall Dock
defaults write com.knollsoft.Rectangle gapSize -float 10
