#!/bin/bash

ver=${1}
if [ -z "${ver}" ]; then
  ver=3
fi

PIP=`which pip${ver} || which pip`
PYTHON=`which python${ver} || which python`
DIR=neovim${ver}

${PIP} install -U pip
${PIP} install -U virtualenv
rm -rf ~/${DIR}
${PYTHON} -m virtualenv ~/${DIR}
source ~/${DIR}/bin/activate
pip install -U neovim
deactivate
