#!/bin/bash

ver=${1}
if [ -z ${ver} ]; then
  ver=3
fi

PIP=$(which pip${ver} || which pip)
${PIP} freeze | xargs ${PIP} uninstall -y
${PIP} install -IU wheel
cat .default-python-packages | xargs ${PIP} install
