#!/bin/bash

ver=${1}
if [ -z "${1}" ]; then
  echo "version is required."
  exit
fi

PIP=`which pip${ver} || which pip`
PYTHON=`which python${ver} || which python`
DIR=neovim${ver}

${PIP} freeze | xargs ${PIP} uninstall -y
${PIP} install -U -I --no-cache-dir pip
${PIP} install -U -I --no-cache-dir -r requirements.txt
test ${ver} = 3 && ${PIP} install black
rm -rf ~/${DIR}
${PYTHON} -m virtualenv ~/${DIR}
source ~/${DIR}/bin/activate
pip install -U neovim
deactivate
