#!/bin/bash

BASEDIR=$(pwd)

git pull -p

# vim-plug
[ -e ~/.config/nvim/autoload/plug.vim ] || curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

[ -e ~/.zplug/init.zsh ] || git clone https://github.com/zplug/zplug ~/.zplug

[ -z "$(git config --global --get init.templatedir)" ] && git config --global init.templatedir ~/.git_template
[ -z "$(git config --global --get core.excludesfile)" ] && git config --global core.excludesfile ~/.gitignore_global

# anyenv
[ -e ~/.anyenv ] || git clone https://github.com/anyenv/anyenv ~/.anyenv
[ -e ~/.config/anyenv/anyenv-install ] || ~/.anyenv/bin/anyenv install --init
[ -e ~/.anyenv/plugins/anyenv-update ] || git clone https://github.com/znz/anyenv-update ~/.anyenv/plugins/anyenv-update

# reset link
for link in ~/.* ~/.config/* ~/.config/nvim/*; do [ -L $link ] && unlink $link; done

# root dotfiles
for name in .*; do [[ ${name} =~ \.(config|git|tags|[A-Z].*|\.)?$ ]] || ln -fs ${BASEDIR}/${name} ~/${name} ;done

mkdir -p ~/.config
for name in .config/*; do
  [ -f ${name} ] && ln -fs ${BASEDIR}/${name} ~/${name} && continue
  mkdir -p ~/${name} && for conf in ${name}/*; do ln -fs ${BASEDIR}/${conf} ~/${conf}; done
done

nvim +:PlugInstall +:PlugClean +:qa
