#!/bin/bash

git fetch -p
git merge origin/master

# vim-plug
[ -e ~/.vim/autoload/plug.vim ] || curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

[ -e ~/.zplug/init.zsh ] || git clone https://github.com/zplug/zplug ~/.zplug

# filetype conf
for name in `ls -a`; do
  if [ -d ${name} ]; then
    [ ${name:0:1} = '.' ] && continue
    [ -L ~/.vim/${name} ] && continue

    rm -rf ~/.vim/${name}
    ln -fs `pwd`/${name} ~/.vim/${name}
    continue
  fi

  [ ${name:0:1} = '.' ] && ln -fs `pwd`/${name} ~/${name}
done

[ -L ~/.config/nvim ] || ln -fs ~/.vim ~/.config/nvim
[ -L ~/.config/nvim/init.vim ] || ln -fs ~/.vimrc ~/.config/nvim/init.vim

test -e ~/.config || mkdir ~/.config
for name in `ls -a .config`; do
  [ ${name:0:1} = '.' ] && continue

  if [ -f .config/${name} ]; then
    [ -L ~/.config/${name} ] && continue
    ln -fs `pwd`/.config/${name} ~/.config/${name} && continue
  fi

  [ -L ~/.config/${name} ] && unlink ~/.config/${name}
  [ -e ~/.config/${name} ] || mkdir ~/.config/${name}
  for conf in .config/${name}/*; do
    [ -L ~/${conf} ] && continue
    ln -fs `pwd`/${conf} ~/${conf}
  done
done

[ -L ~/.pip ] || ln -fs `pwd`/.pip ~/.pip
[ -L ~/.git_tmp ] || ln -fs `pwd`/.git_tmp ~/.git_tmp
[ -L ~/.ctags.d ] || ln -fs `pwd`/.ctags.d ~/.ctags.d

[ -z "$(git config --global --get init.templatedir)" ] && git config --global init.templatedir ~/.git_tmp
[ -z "$(git config --global --get core.excludesfile)" ] && git config --global core.excludesfile ~/.gitignore_global

# del dead link
for link in ~/.* ~/.config/*; do
  [ -L $link ] || continue
  [ -e "$(readlink $link)" ] && continue
  unlink $link
done

nvim +:PlugInstall +:q +:PlugClean +:q +:q
