#!/bin/bash

# vim-plug
[ -e ~/.config/nvim/autoload/plug.vim ] || curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

[ -e ~/.zplug/init.zsh ] || git clone https://github.com/zplug/zplug ~/.zplug

# mise
mise install

./sync_dotfiles

$EDITOR +PlugInstall +qa
