#!/bin/bash

# reset link
for link in ~/.* ~/.config/* ~/.config/nvim/*; do [ -L ${link} ] && unlink ${link}; done

# root dotfiles
for name in .*; do [[ ${name} =~ \.+(config|git(ignore|config)?|tags|eslintrc\..*|[A-Z].*)?$ ]] || ln -fs $(pwd)/${name} ~/${name}; done
for name in .gitconfig; do [[ -e ~/${name} ]] || cp -f ${name} ~/${name}; done

mkdir -p ~/.config
for name in .config/*; do
  [ -f ${name} ] && ln -fs $(pwd)/${name} ~/${name} && continue
  mkdir -p ~/${name} && for conf in ${name}/*; do ln -fs $(pwd)/${conf} ~/${conf}; done
done
