#!/bin/bash

GO111MODULE=off go get -u \
  github.com/mithrandie/csvq \
  github.com/cweill/gotests/... \
  golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow

pip3 install -IU poetry pipdeptree

npm i -g sql-formatter-cli
