#!/bin/bash

set -e

asdf plugin update --all

for plugin in $(cat .tool-versions | cut -f1 -d " "); do
  asdf install ${plugin} latest
  asdf global ${plugin} latest
  asdf local ${plugin} latest
done

asdf direnv setup --shell zsh --version latest
