#!/usr/bin/env zsh

gotools=(
  golang.org/x/tools/gopls
  github.com/cweill/gotests/...
  github.com/ChimeraCoder/gojson/gojson
  honnef.co/go/tools/cmd/staticcheck
  golang.org/x/tools/cmd/goimports
)

for repo in ${gotools[@]}; do
  go install ${repo}@latest
done
