#!/bin/bash

set -e

git pull -p
./sync_dotfiles

type brew > /dev/null 2>&1 && brew upgrade; brew cleanup

${EDITOR} +PlugUpgrade +PlugInstall +PlugUpdate +qa
[[ ${EDITOR} = 'nvim' ]] && ${EDITOR} +UpdateRemotePlugins +qa

gotools=(
  golang.org/x/tools/gopls
  github.com/cweill/gotests/...
  mvdan.cc/gofumpt
  github.com/golangci/golines
  github.com/ChimeraCoder/gojson/gojson
  honnef.co/go/tools/cmd/staticcheck
  golang.org/x/tools/cmd/goimports
)

for repo in ${gotools[@]}; do
  go install ${repo}@latest
done

pushd ~/.zplug && git pull -p && popd
zsh -c 'source ~/.zplug/init.zsh; zplug update'
